### ISSUE TITLE
NotWorking

### ISSUE THREAD

**Issue by ghost** [chinoogawa/instaBrute#1]
Tested on my account and it isnt working

**Comment by neutt22** [comment]
Hi. Can you at least show a screenshot and test dictionary text file with at least 3 passwords

**Comment by c0f1** [comment]
![screenshot from 2015-11-09 01 25 42](https://cloud.githubusercontent.com/assets/12828213/11038351/6b4a267a-86fa-11e5-8930-cba8b625dc24.png)

**Comment by neutt22** [comment]
Did you have the true password on the dictionary file?

**Comment by c0f1** [comment]
Yes ofcourse i tryed with real one.

**Comment by neutt22** [comment]
Then this software is busted. I hope the owner updates this

**Comment by chinoogawa** [comment]
Is not busted, and I don't see a bug there. Can you give me additional information about what's going on? 
If the password is in the dictionary file, it should work fine.

**Comment by c0f1** [comment]
Do u see screenshot its not working ...

**Comment by neutt22** [comment]
@chinoogawa  Maybe it would be a lot better if you could state the versions the library is using?

**Comment by chinoogawa** [comment]
@ghost I saw the screenshot. Could you send me the dictionary? Maybe when you added the passwords to the file some weird character was added too. I've been testing the tool and is working fine. 
Additionally, I'm going to write down the library version just in case.

**Comment by mehmetemek** [comment]
@chinoogawa I sent an e-mail to you. Can you check it?
