### ISSUE TITLE
eror in run tools

### ISSUE THREAD

**Issue by testtoolspy** [chinoogawa/instaBrute#14]
hello
i run tools and se erro :100: 

File "C:\Users\\Downloads\instaBrute-master\instaBrute-master\instaBrute.py", line 2, in <module>
    from mainLib import *
  File "C:\Users\\Downloads\instaBrute-master\instaBrute-master\mainLib.py", line 1, in <module>

**Comment by aleperno** [comment]
Could you please attach the full error trace?

**Comment by testtoolspy** [comment]
![2016-05-11_154654](https://cloud.githubusercontent.com/assets/19265516/15179947/c89904c4-178f-11e6-9854-27f6c94f8acf.png)


attached

**Comment by Coto16** [comment]
For windows, it might be "py" instead of "python". So try: py instaBrute.py -f usernames.txt -d dictionary.txt

**Comment by testtoolspy** [comment]
C:\Users\Administrator\Desktop\in>py instaBrute.py -f usernames.txt -d dictionar
y.txt
'py' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Coto16** [comment]
You probably haven't installed Python on your System properly then. Lookup some tutorials on how to do that and come back if you have any more errors.

**Comment by testtoolspy** [comment]
![2016-05-12_042432](https://cloud.githubusercontent.com/assets/19265516/15213673/d5376570-1859-11e6-8487-0a8593492a4a.png)


windows server..

**Comment by Coto16** [comment]
The best guess would be to google it, I really don't use Python on Windows/Windows Server. I use it in Kali Linux, so, I can't help you with that, sorry.

**Comment by aleperno** [comment]
@testtoolspy you're missing the module ```mechanize```.
Since I'm not very familiar with python in Windows all I could say is to refer to any search engine of your choice.
Try to install ```pip``` (a python package installer) and then 
```pip install mechanize```
The same should apply to any other missing module you could encounter.
