### ISSUE TITLE
No module named simplejson

### ISSUE THREAD

**Issue by Hazzkm** [chinoogawa/instaBrute#15]
![untitle](https://cloud.githubusercontent.com/assets/19402307/15312806/a92f1d88-1c0f-11e6-952b-3643887d3531.jpg)

**Comment by Coto16** [comment]
https://www.google.com/search?q=install%20simplejson&cad=h

**Comment by aleperno** [comment]
First make sure you have ```pip``` and the necessary packates to install python modules
```apt-get install python-pip python-dev build-essential```
Then you should just
```pip install simplejson```
