### ISSUE TITLE
line 19, print 'user: "%s" does not exist, trying with the next!' %username ^ SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by dmorrison2k** [chinoogawa/instaBrute#17]
I'm having this error:

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32> python instaBrute.py -f usernames.txt -d dictionary.txt
python: can't open file 'instaBrute.py': [Errno 2] No such file or directory

C:\WINDOWS\system32>instaBrute -h
'instaBrute' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>cd C:\Users\Devin\Desktop\instaBrute

C:\Users\Devin\Desktop\instaBrute>python instaBrute.py -f usernames.txt -d dictionary.txt
  File "instaBrute.py", line 23
    print 'user: "%s" does not exist, trying with the next!' %username
                                                           ^
SyntaxError: Missing parentheses in call to 'print'

C:\Users\Devin\Desktop\instaBrute>python instaBrute.py -f usernames.txt -d dictionary.txt
  File "instaBrute.py", line 23
    print 'user: "%s" does not exist, trying with the next!' %username
                                                           ^
SyntaxError: Missing parentheses in call to 'print'

C:\Users\Devin\Desktop\instaBrute>

---------------------
Please help.

**Comment by Coto16** [comment]
Try replacing line 19 with: 		print 'user: ' +user+ ' does not exist, trying with the next!'

**Comment by aleperno** [comment]
You are using Python 3 while this code is for Python 2.7

**Comment by dmorrison2k** [comment]
Thanks everyone. Will send some feedback today.
