### ISSUE TITLE
Help Dependencies

### ISSUE THREAD

**Issue by Hugi21** [chinoogawa/instaBrute#2]
Hi everyone , I have an error with Dependencies please help me for solve this problem.

http://hpics.li/7f585d4

(PS:Basic I am not Python developer so do not yell at me too top)

**Comment by chinoogawa** [comment]
First you need to download and install "easy_install" or "setuptools" for python. 
Once you've install that, you have to set the system environment variable PATH to the setuptools folder, that way you can call the "pip" command from the CMD. Then, you have to install the dependency with the command "pip install mechanize" from the command line.

**Comment by gflores123** [comment]
i have the same problem, except i only get -
Traceback (most recent call last):
  File "instaBrute.py", line 2, in <module>
    from mainLib import *
ImportError: No module named mainLib

I have already installed easy_install/setuptools but i always get the ' importError: No module named mainLib ' i have also tried pip install mainLib , i am new to using python.. any help? thank youu :+1:

**Comment by chinoogawa** [comment]
@gflores123 you should have the manLib.py script from instabrute in the same folder you have the instaBrute.py.
Please check that all the scripts for instaBrute were downloaded correctly.
