### ISSUE TITLE
Webdriver Problem

### ISSUE THREAD

**Issue by uknowyosa** [chinoogawa/instaBrute#23]
can anyone fix this problem? im stucking in this :( thank u
![capture](https://cloud.githubusercontent.com/assets/21298042/18037321/1ed3e838-6dab-11e6-8ba2-c26b2d05acdd.PNG)

**Comment by djscoobyg2** [comment]
By the looks of it you need to have the exact version of selenium which is
3.0.0b2
and python 2.7

**Comment by moain** [comment]
I have this error too. i use selenium 3.0.0b2 and python 2.7.12 firefox 48 
someone help me i need to fix it

**Comment by ItsMas** [comment]
Also having this error, I have selenium 3.0.0b2 and Firefox 48.0.2

**Comment by djscoobyg2** [comment]
Guys, its just easier to get a VM of any linux and install it there.

**Comment by ItsMas** [comment]
Went through the hassle of setting up a Linux VM and got the same error ;-;

**Comment by uknowyosa** [comment]
solved, 3.0.0b2 is compatible with firefox 45, i try this and sucessfully worked

**Comment by ItsMas** [comment]
Unfixed ^-^ Still get the same error with Firefox 45.0

**Comment by ItsMas** [comment]
Still not working for me, using seleniun 3.0.0b2, firefox 45.0
