### ISSUE TITLE
getting problem HELP!

### ISSUE THREAD

**Issue by a3lharbi** [chinoogawa/instaBrute#3]
when i run the script im getting this output 

Trying with username: hacker
Trying with password: Passw0rd
405
Trying with password: password01
405
user: "qwerty" does not exist, trying with the next!
Trying with username: facebook
Trying with password: Passw0rd
405
Trying with password: password01
405
Trying with username: inexistente
Trying with password: Passw0rd
405
Trying with password: password01
405

i dont know why im getting 405 , and i did'nt show me if the password right or wrong

**Comment by Nas-au** [comment]
I'm getting the same error as well!

**Comment by arty0m** [comment]
have the same problem

**Comment by chinoogawa** [comment]
Working on a fix! Thanks for reporting ;)

**Comment by a3lharbi** [comment]
thanks for answering im gonna wait  ;) .

**Comment by Coto16** [comment]
Same issue here, but I'll just wait for the Dev to fix it! Let us know how you're getting on with it, @chinoogawa ! :+1:  :smiley:

**Comment by Coto16** [comment]
Any updates on the Fix, @chinoogawa (Dev)? Really can't wait for this to be fixed!

**Comment by chinoogawa** [comment]
Thanks for reporting! The fix has been dispatched ;) enjoy and let me know if something comes up with the new implementation. 
You'll need to get the dependencies for the selenium ;)

Merry Christmas hackers!!

**Comment by Coto16** [comment]
Still not working... :(

Date: Thu, 24 Dec 2015 07:40:12 -0800
