### ISSUE TITLE
This tool is completely unusuable

### ISSUE THREAD

**Issue by Yesssaag** [chinoogawa/instaBrute#39]
Isn't this tool basically pointless. When you go to the instagram login page it says "there was a problem logging you in please try again later" after about 10 tries. And I've tried using the version with proxy support and tor, it still does not work. 

So can someone find a way to bypass this

**Comment by 0xCoto** [comment]
Oh my God. When will people realize this has been patched months ago?

**Comment by Yesssaag** [comment]
if this tool has been patched then someone delete this project from github its a waste of space/time

**Comment by 0xCoto** [comment]
You clearly do not know what Github is used for.

**Comment by Yesssaag** [comment]
It's purpose is to share code/improve it but why share unusuble code that can't be improved?

**Comment by 0xCoto** [comment]
The code can not be used solely for instagram.

**Comment by chinoogawa** [comment]
I agree with @0xCoto. The tool can be reused for other purposes.
If you check FBHT you realize that part of instabrute it's inspired on fbht's code.
If I get a way to bypass the instagram login again, I'll let you know ;)

**Comment by aleperno** [comment]
@Yesssaag For future reference keep in mind people would be far more willing to solve your inquires if you change your wording a bit or include a 'please' / 'thanks'.

Is this script outdated? Yeah, no doubt.
Is it useless? Not quite, It may not be doing what It claims it does (and at some point did), BUT it source being open may be useful for others seeking for a starting point.
You can download it, fork it, modify it, propose pull requests.
