### ISSUE TITLE
Still not working (After Update)

### ISSUE THREAD

**Issue by Coto16** [chinoogawa/instaBrute#4]
https://i.gyazo.com/d85e2e768c72a0ca8307027cb874d78b.png

When I do python instaBrute.py -u meiko_dew -d dictionary.txt it opens up a browser window, going to https://www.instagram.com/meiko_dew/ then https://www.instagram.com/accounts/login/ , tries some passwords and just displays wrong password...

**Comment by Nas-au** [comment]
The same here 

I tried it on Mac Os and Kali

**Comment by Coto16** [comment]
Even after doing pip install -U selenium

still displays another, wrong password...

**Comment by Coto16** [comment]
I think I found what the error is, but not sure how to fix it.

On the instaBrute.py script (Line 24-31):

def login(user, password):
	try:
		print 'Trying with password: ' + password
		elem = driver.find_element_by_name("username")
		elem.send_keys(user)
		elem = driver.find_element_by_name("password")
		elem.send_keys(password)  
		elem.send_keys(Keys.RETURN)

I noticed that it opens the Web Browser, and types the next password without deleting the previous one.

So if dictionary.txt was included the following lines:

Password
test123
mypass123
...

Then it would try the attempts:

Attempt 1) Trying with password: Password
Attempt 2) Trying with password: Passwordtest123
Attempt 3) Trying with password: Passwordtest123mypass123

Instead of:

Attempt 1) Trying with password: Password
Attempt 2) Trying with password: test123
Attempt 3) Trying with password: mypass123

So I think it should include these attributes:

ActionChains(driver).key_down(Keys.CONTROL).send_keys('a').key_up(Keys.CONTROL).perform()
(That would select all the text(password) - CTRL + a)

elem.send_keys(Keys.DELETE) or elem.send_keys(Keys.BACKSPACE) or elem.send_keys(Keys.BACK_SPACE)
(That would delete the selected password - Delete/Backspace button)

But I'm not sure how to add this to the code, so hopefully the Dev, @chinoogawa can look into that!

(P.S.: To be honest, I enjoyed the Terminal - cool looking - way to crack Instagram Passwords, or at least I'd rather the Browser not to show up at all, but if that's not possible, let's at least try to fix this major bug!)

**Comment by chinoogawa** [comment]
Hi Guys! Thanks for the data. I totally forgot to put the clear instruction on every try!! 
Now i'm facing a new trouble in wich I can't determine if an account was logged in or not. The error code does not appear in the page source, so I need to get some logic clue to flag a logged in try. 
Working on a fix, promise :D

**Comment by chinoogawa** [comment]
Okey, fixed now! Please let me know if works as it should :D if it works, i close the issue!!
Have a nice day

**Comment by Coto16** [comment]
Looks like @HusamSadawi and I worked together to bring on a fix. But thanks to @chinoogawa for fixing the issue for everyone! :+1:  :smile:

**Comment by Nas-au** [comment]
Good job , it's working but the new problem is that i got blocked after some time.
if you could make proxy list so that after 25 try the proxy changes that would be grate.
Thanks a lot @chinoogawa for your amazing peace of code and thank you all for the teamwork  :+1:

**Comment by Coto16** [comment]
Just noticed that too, thanks for the report, @Nas-au . Will be working on a fix as soon as possible.

**Comment by Nas-au** [comment]
Thanks @Coto16

**Comment by chinoogawa** [comment]
Thanks @Coto16 and @Nas-au for the tips ;) I'll work on the proxy feature. The bruteforce blocking from instagram is new and recently. This tool was made for that reason jeje. Now we've to manage to bypass the new security measures !
