### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kaktoos81** [chinoogawa/instaBrute#5]
hello
i get this error
how to fix it?
http://s6.picofile.com/file/8230007118/error.png

**Comment by Coto16** [comment]
Got skype? if so add me: iLouisy

Date: Sat, 26 Dec 2015 07:18:35 -0800

**Comment by Coto16** [comment]
Make sure you use Python 2.7 and retry. If you get another error, unrelated to the script, but its performance, that's normal. Currently working on a fix.

**Comment by chinoogawa** [comment]
@kaktoos81 as @Coto16 says, you are using python >= 3 and instaBrute works with 2.7 :) 
Thanks @Coto16 for the response!
