### ISSUE TITLE
Web Implementation Errors

### ISSUE THREAD

**Issue by HusamSadawi** [chinoogawa/instaBrute#6]
A couple of errors I've found with the last update:
The inputs from previous trials do not get deleted, I noticed that when the login page is loaded and passwords are prompted, the program does not remove the old tried password before going to the next one, same for the username. Saying your username is "Hello", after every failed try it will just keep  typing a new "Hello" added to the previous ones as a user name, so on the second try it'd be "HelloHello"
But the real issue is that (for me), FireFox just quits after trying all the possible combinations, this happened even when I provided my own correct username and password.

I'm sure you'd work these out, generally speaking, a very neat piece of code!

**Comment by Coto16** [comment]
^ Check out my other Issue I created. Saying that exactly and provided a solution. :)

**Comment by HusamSadawi** [comment]
Nice solution, I guess this one is easy to implement by myself, the real issue though is the browser quitting, does that happen with you? If not, what's your OS?

**Comment by Coto16** [comment]
Nope, it doesn't close. For me it opens IceWeasel and does everything wrongly without closing. Could you please send the fix for the script?

**Comment by HusamSadawi** [comment]
Weird, I tried running the code on both Windows10 and Kali 2, both cases firefox/iceweasel just shuts down.
I'm more focused on fixing this issue of the browser closing for now, 'cause it's keeping the rest of the check from working.
But, since your browser doesn't work, what happens when you provide correct username and password from the first try? It should work, does it?

**Comment by Coto16** [comment]
I assume so, yeah. Have you got Skype by the way? If so, add me: iLouisy

**Comment by HusamSadawi** [comment]
I did some minor edits on the code, and it's working now, some of them were optimized for my case, it seemed like the browser closes upon end of the code, which's ok, but the problem was with the wait time, apparently. I added a delay of 2 seconds between tries, which's not very good for brute forcing, but it does the trick for now. Anyways, it's attached, but it depends on your internet connection, so if you have a slow one, you'd want to edit the delay time for more than just 2 seconds. One last word on the edits, I haven't read the entire code (very bad practice of me, but I don't have time), so I'm not sure what cases would this cause to fail. 
Will add you on skype, got you

[instaBrute.zip](https://github.com/chinoogawa/instaBrute/files/72664/instaBrute.zip)

**Comment by Coto16** [comment]
"An error occurred while extracting the files"

**Comment by Coto16** [comment]
Could you please paste the script code on Pastebin or zip it in rar instead of .zip or something?

**Comment by Coto16** [comment]
Also, I never received a Skype request from you. Mind telling me your skype?

**Comment by HusamSadawi** [comment]
Sorry for not mentioning this earlier, it's actually a rar file not a zip file, just fake extension to upload to github, change to .rar

**Comment by chinoogawa** [comment]
As @HusamSadawi says, i'm facing some timing issues in the code. When we try to verify a login, the "wrong code" legend does not appear in the page source.. So i'm looking how to fix this. 
Sorry about the delay!

**Comment by chinoogawa** [comment]
Okey, fixed now! Please let me know if works as it should :D if it works, i close the issue!!
Have a nice day

**Comment by chinoogawa** [comment]
BTW, new options was added for timing problems! Now you can set the -t options for the delay.
