### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kaktoos81** [chinoogawa/instaBrute#7]
after run the command get me the error:

Traceback (most recent call last):
  File "instaBrute.py", line 4, in <module>
    from selenium import webdriver
ImportError: No module named selenium

i use python 2.7.9
any body help me?

**Comment by Nas-au** [comment]
use the command to install selenium package 

pip install selenium

**Comment by kaktoos81** [comment]
nice...
who can run this at winserver 2008?
i install python v2.7 in winserver but it not work an error accour
'python' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Coto16** [comment]
I think you'll need to search this on Google as the issue is not related to the Module. Good luck!
